apiVersion: v1
kind: Service
metadata:
  name: rippled-zig
  labels:
    app.kubernetes.io/name: rippled-zig
    app.kubernetes.io/component: network
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: rippled-zig
  ports:
    - name: rpc
      port: 5005
      targetPort: rpc
      protocol: TCP
    - name: peer
      port: 51235
      targetPort: peer
      protocol: TCP
    - name: websocket
      port: 6006
      targetPort: websocket
      protocol: TCP
